language: node_js
sudo: false

# test on two node.js versions: 0.10 0.12
node_js:
  - 0.10
    #  - 0.12

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
#notifications:
#  irc: "irc.freenode.org#travis"

